# ================= ConfigMap =================
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-consumer-apis-config
data:
  SERVER_PORT: "9020"
  MONGODB_DATABASE: "cms_db_admin"
  PROFILE: "st"
  KAFKA_GROUP: "DEV_CMS_NOTIFICATION"
  SMS_TOPIC: "DEV_CMS_NOTIFICATION_SMS"
  EMAIL_TOPIC: "DEV_CMS_NOTIFICATION_EMAIL"
  CALLBACK_TOPIC: "DEV_CMS_NOTIFICATION_CALLBACK"
  PATNER_PORTAL_APIS_URL: "http://patner-portal-apis:9002"
  SYSTEM_REGISTRY_APIS_URL: "http://system-registry-apis:9011"

---
# ================= Deployment =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer-apis
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: notification-consumer-apis
  template:
    metadata:
      labels:
        app: notification-consumer-apis
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: notification-consumer-apis
          image: "$(IMAGE_URL)"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: notification-consumer-apis-config
          env:
            - name: KRB5_CONFIG
              value: /etc/krb5.conf
            - name: KEYTAB_CONFIG
              value: /etc/si_digigov.keytab
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
          volumeMounts:
            - name: logs
              mountPath: /opt/logs
            - name: krb5-conf-volume
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
              readOnly: true
            - name: krb5-keytab-volume
              mountPath: /etc/si_digigov.keytab
              subPath: si_digigov.keytab
              readOnly: true
      volumes:
        - name: logs
          emptyDir: {}
