package com.jio.multitranslator.exceptions;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public class TranslateException extends RuntimeException {

    private final HttpStatus httpStatus;
    private final String errorMessage;

    public TranslateException(String message, HttpStatus httpStatus, String errorMessage) {
        super(message);
        this.httpStatus = httpStatus;
        if ("Bhashini Generated".equals(message)) {
            this.errorMessage = errorMessage != null 
                    ? errorMessage + " (Generated by Bhashini service)" 
                    : "Generated by Bhashini service";
        } else {
            this.errorMessage = errorMessage;
        }
    }

}
