package com.jio.schedular.enums;

public enum Action {
    GRIEVANCE_ESCALATION,
    CONSENT_EXPIRED,
    CONSENT_PREFERENCE_EXPIRY_REMINDER,
    CONSENT_HANDLE_EXPIRY,
    CONSENT_ARTIFACT_RETENTION,
    COOKIE_CONSENT_RETENTION,
    DATA_RETENTION,
    LOGS_RETENTION,
    GRIEVANCE_RETENTION,
    COOKIE_CONSENT_HANDLE_EXPIRED,
    COOKIE_CONSENT_EXPIRED;
}