package com.jio.schedular.enums;

public enum AuditComponent {
    CONSENT_EXPIRED,
    CONSENT_HANDLE_EXPIRED,
    CONSENT_PREFERENCE_EXPIRY_REMINDER,
    GRIEVANCE_ESCALATION,
    CONSENT_ARTIFACT_RETENTION,
    COOKIE_CONSENT_RETENTION,
    DATA_RETENTION,
    LOGS_RETENTION,
    GRIEVANCE_RETENTION,
    COOKIE_CONSENT_EXPIRED,
    COOKIE_CONSENT_HANDLE_EXPIRED,
    CONSENT_AUTO_RENEWAL;
}