package com.jio.schedular.enums;

public enum JobName {
    CONSENT_ARTIFACT_RETENTION_JOB,
    CONSENT_EXPIRY_JOB,
    CONSENT_HANDLE_EXPIRY_JOB,
    CONSENT_PREFERENCE_EXPIRY_NOTIFICATION_JOB,
    COOKIE_CONSENT_EXPIRY_JOB,
    COOKIE_CONSENT_HANDLE_EXPIRY_JOB,
    COOKIE_CONSENT_RETENTION_JOB,
    DATA_RETENTION_JOB,
    GRIEVANCE_ESCALATION_JOB,
    GRIEVANCE_RETENTION_JOB,
    LOGS_RETENTION_JOB;
}