spring.application.name=consent
server.servlet.context-path=/consent
server.port=${SERVER_PORT:9001}
log_path=/log/consent
path.to.json.file=/opt/props/
#spring.data.mongodb.uri=mongodb://<user>:<password>@<host>:27017/?authSource=admin
#spring.data.mongodb.database=cms_db_admin

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/?authSource=admin}
spring.data.mongodb.database=${MONGODB_DATABASE:cms_db_admin}
#spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.index.ensure-indexes=true

spring.servlet.multipart.max-request-size=10MB
file.max.size.bytes=10485760
file.allowed.document.types=application/pdf

logging.http.trace.enabled=false

spring.profiles.active=${PROFILE:dev}

templates.search.parameters=templateId,version,businessId
handles.search.parameters=templateId,templateVersion,status,customerIdentifiers.type,customerIdentifiers.value
consent.search.parameters=consentId,status,businessId,templateId,consentHandleId,customerIdentifiers.type,customerIdentifiers.value

notification.service.base.url=${NOTIFICATION_MODULE_APIS_URL:http://localhost:30005}
notification.service.endpoints.trigger-event=/notification/v1/events/trigger

audit.service.base.url=${AUDIT_MODULE_APIS_URL:http://localhost:30006}
audit.service.endpoints.audit=/audit/v1/audit

vault.service.base.url=${VAULT_APIS_URL:http://localhost:30010}
vault.service.endpoints.sign=/client/sign
vault.service.endpoints.verify=/client/verify
vault.service.endpoints.encryptPayload=/client/encryptPayload

auth.service.base.url=${AUTH_APIS_URL:http://localhost:30009}
auth.service.endpoints.createSecureCode=/secureCode/create

registry.service.base.url=${REGISTRY_APIS_URL:http://localhost:30011}
registry.service.endpoints.withdraw-consent=/registry/api/v1/consents/{consentId}/withdraw

# Parental Consent Configuration
parental.consent.redirect.base.url=${PARENTAL_CONSENT_REDIRECT_BASE_URL}
parental.consent.callback.url=${PARENTAL_CONSENT_CALLBACK_URL}

spring.jackson.serialization.write-dates-as-timestamps=false

# DigiLocker Properties
digilocker.base.url=https://api.digitallocker.gov.in
digilocker.proxy.enabled=${PROXY_ENABLED:false}
#digilocker.proxy.host=${PROXY_HOST}
digilocker.proxy.host=${PROXY_HOST:}
digilocker.proxy.port=${PROXY_PORT:8080}

# Batch processing configuration
template.handle.creation.batch.size=${TEMPLATE_HANDLE_BATCH_SIZE:1000}

# JWS Signature configuration
jws.signature.enabled=${JWS_SIGNATURE_ENABLED:false}