spring.application.name=partnerportal
server.servlet.context-path=/partnerportal
server.port=${SERVER_PORT:9002}
app.logging.dir=logs/partnerportal
path.to.json.file=/opt/props/
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/?authSource=admin}
spring.data.mongodb.database=${MONGODB_DATABASE:cms_db_admin}
spring.data.mongodb.auto-index-creation=true
spring.profiles.active=${PROFILE:dev}


spring.jackson.serialization.write-dates-as-timestamps=false
x-session-token.enable=true
security.2fa.enabled=${2FA:false}

max_retry = 3
otp.time.to.live= PT10M
auth.secret.time.to.live= PT3M

http.client.connect-timeout=5000
http.client.read-timeout=5000

#Encryption algorithm
jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256

tenants.search.parameters=tenantId,pan
legal-entity.search.parameters=legalEntityId,companyName
smtp.search.parameters=businessId,scopeLevel,configId
smsc.search.parameters=businessId,scopeLevel,configId
grievance.search.parameters=businessId,scopeLevel,configId
consent.search.parameters=businessId,scopeLevel,configId
dpo.search.parameters=businessId,scopeLevel,configId
ropa.search.parameters=businessId,ropaId
purpose.search.parameters=
dataType.search.parameters=
dataProcessor.search.parameters=
processorActivity.search.parameters=${PROCESSOR_SEARCH_PARAMS:processorActivityId}
systemConfig.search.parameters=businessId,scopeLevel,configId
businessApplication.search.parameters=businessId
config-history.search.parameters=configType,businessId,operation,performedBy
client-credentials.search.parameters=businessId,businessUniqueId,consumerKey,scopeLevel,certType
notification.search.parameters=businessId,scopeLevel,configId
digilocker.credential.search.parameters=credentialId,clientId,businessId,scopeLevel,status

# Configure the WSO2 provider details
spring.security.oauth2.client.provider.wso2-provider.token-uri=${wso2.token.url}

# WSO2 Service Configuration
wso2.service.base.url=${WSO2_CRED_GENERATOR_APIS_URL:http://localhost:30004}/api/v1
wso2.service.endpoints.register-tenant=/registerTenant
wso2.service.endpoints.onboard-business=/onboardBusiness
wso2.service.endpoints.onboard-dataprocessor=/onboardDataProcessor

# Vault Service Configuration
vault.service.base.url=${VAULT_APIS_URL:http://localhost:30010}
vault.service.endpoints.onboard-key=/client/key/onboard
vault.service.endpoints.sign=/client/sign

# Auth Service Configuration
auth.service.base.url=${AUTH_APIS_URL:http://localhost:30009}
auth.service.endpoints.token=/oauth2/token

# Notification Service Configuration
notification.service.base.url=${NOTIFICATION_MODULE_APIS_URL:http://localhost:30005}
notification.service.endpoints.onboarding-setup=/notification/v1/onboarding/setup
notification.service.endpoints.trigger-event=/notification/v1/events/trigger
notification.service.endpoints.system-trigger-event=/notification/v1/system/events/trigger
notification.service.endpoints.system-verify-otp=/notification/v1/system/otp/verify
notification.service.provider.type=DIGIGOV

# Audit Service Configuration
audit.service.base.url=${AUDIT_MODULE_APIS_URL:http://localhost:30006}
audit.service.endpoints.audit=/audit/v1/audit

# Portal URL Configuration
portal.url=${PORTAL_URL:https://partnerportal.example.com}