# ================= ConfigMap =================
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-module-apis-config
data:
  SERVER_PORT: "9006"
  MONGODB_DATABASE: "cms_db_admin"
  PROFILE: "st"
  KAFKA_GROUP: "DEV_CMS_NOTIFICATION"
  AUDIT_TOPIC: "DEV_CMS_NOTIFICATION_AUDIT"
  VAULT_APIS_URL: "http://vault-apis:9010"
  NOTIFICATION_MODULE_APIS_URL: "http://notification-module-apis:9005"

---
# ================= Deployment =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-module-apis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: audit-module-apis
  template:
    metadata:
      labels:
        app: audit-module-apis
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: audit-module-apis
          image: "$(IMAGE_URL)"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 9006
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: audit-module-apis-config
          env:
            - name: JAVA_OPTS
              value: "-Djava.security.krb5.conf=/etc/krb5.conf"
            - name: KRB5_CONFIG
              value: /etc/krb5.conf
            - name: KEYTAB_CONFIG
              value: /etc/si_digigov.keytab
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
          volumeMounts:
            - name: logs
              mountPath: /opt/logs
            - name: krb5-conf-volume
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
              readOnly: true
            - name: krb5-keytab-volume
              mountPath: /etc/si_digigov.keytab
              subPath: si_digigov.keytab
              readOnly: true
      volumes:
        - name: logs
          emptyDir: {}
        - name: krb5-conf-volume
          secret:
            secretName: kafka-krb5
        - name: krb5-keytab-volume
          secret:
            secretName: kafka-keytab

---
# ================= Service =================
apiVersion: v1
kind: Service
metadata:
  name: audit-module-apis
spec:
  type: NodePort
  selector:
    app: audit-module-apis
  ports:
    - protocol: TCP
      port: 9006
      targetPort: 9006
      nodePort: 30006
