spring.application.name=auth
server.port=${SERVER_PORT}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false



#token cache
token.cache.type=inMemory
token.cache.maximum-size=10001
token.cache.expire-after-minutes=60
whitelistips.file.path=whitelisted-ips.json
whitelistips.check = false

token.expiry = 3600000
token.max.sessions = 1
securecode.expiry = 60
wso2.token.url=${WSO2_BASE_URL}/oauth2/token

audit.url=${AUDIT_MODULE_APIS_URL:http://localhost:30006}/audit/v1/audit

app.sign.response = ${APP_SIGN:false}
app.verify.request = ${APP_VERIFY:false}


