spring.application.name=negd

server.port=${SERVER_PORT}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
vault.base-url=${EXT_VAULT_URL:http://localhost:8200}
vault.encrypt-uri=/v1/transit/encrypt/
vault.decrypt-uri=/v1/transit/decrypt/
vault.sign-uri=/v1/transit/sign/test-key2/sha2-256
vault.verify-uri=/verify/test-key2
# Set ROOTKEY via environment (Vault token)
vault.token=${ROOTKEY}





