package com.jio.partnerportal.dto;

public enum AuditComponent {
    AUTHENTICATION,
    BUSINESS_APPLICATION,
    CONSENT_CONFIG,
    CONSENT_SIGNING_KEY,
    DATA_BREACH_REPORT,
    DATA_PROCESSOR,
    DATA_TYPE,
    DIGILOCKER_CREDENTIAL,
    DPO_CONFIG,
    GRIEVANCE_CONFIG,
    LEGAL_ENTITY,
    NOTIFICATION_CONFIG,
    PROCESSOR_ACTIVITY,
    PURPOSE,
    ROPA,
    SMSC_CONFIG,
    SMTP_CONFIG,
    SUBSCRIPTION,
    SYSTEM_CONFIG,
    TENANT,
    USER_ROLE,
    USER,
    RETENTION_CONFIG;
}